### PR TITLE
Documentation update: token permissions to include read/write settings

### PR DESCRIPTION
**Pull request by jeanluclariviere**
# Description
Updating README.md to include read/write settings permissions for the API token as this is required for kubernetes-monitoring.

## How can this be tested?
Not required, updating documentation only.

### CODE REVIEW

**Comment by jeanluclariviere** [comment]
Submitting to address issue #675

**Comment by chrismuellner** [comment]
Thanks for pointing this out.
The required scopes were updated recently and can be found here (API token): [Prerequisites](https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/set-up-k8s-monitoring#prerequisites)

If you want to adapt the scopes accordingly, we'd need to change more than add the 2 you added.

**Comment by jeanluclariviere** [comment]
> Thanks for pointing this out. The required scopes were updated recently and can be found here (API token): [Prerequisites](https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/set-up-k8s-monitoring#prerequisites)
> 
> If you want to adapt the scopes accordingly, we'd need to change more than add the 2 you added.

Would it make sense to update the README.md to mirror more or less what's written in the update scope under prerequisites? Or  just provide a reference to the official documentation to avoid having to update this regularly? Or both..

**Comment by luhi-DT** [comment]
Readme has been adapted accordingly with https://github.com/Dynatrace/dynatrace-operator/pull/820 .Token scopes needed in order to run the operator are documented on the official help page as linked in the readme now.

**Pull request closed without merging**
