### PR TITLE
Remove schemaVersion from EdgeConnect Settings object

### PR DESCRIPTION
**Pull request by albertogdd**
## Description

Remove `schemaVersion` from EdgeConnect settings object. It's not necessary.

## How can this be tested?

- Deploy EdgeConnect with `provisioner: true` and `kubernetesAutomation.enabled: true`
- Settings object (located here https://dib18963.dev.apps.dynatracelabs.com/ui/apps/dynatrace.classic.settings/ui/settings/app:dynatrace.kubernetes.connector:connection?gf=all) should be created and deleted after CR deletion

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
> ## Description
> Remove `schemaVersion` from EdgeConnect settings object. It's not necessary.
> 
> ## How can this be tested?
> * Deploy EdgeConnect with `provisioner: true` and `kubernetesAutomation.enabled: true`
> * Settings object (located here https://dib18963.dev.apps.dynatracelabs.com/ui/apps/dynatrace.classic.settings/ui/settings/app:dynatrace.kubernetes.connector:connection?gf=all) should be created and deleted after CR deletion

could you please add ticket link to description?

**Review by andriisoldatenko — APPROVED** [review]

**Comment by albertogdd** [comment]
> > ## Description
> > Remove `schemaVersion` from EdgeConnect settings object. It's not necessary.
> > ## How can this be tested?
> > 
> > * Deploy EdgeConnect with `provisioner: true` and `kubernetesAutomation.enabled: true`
> > * Settings object (located here https://dib18963.dev.apps.dynatracelabs.com/ui/apps/dynatrace.classic.settings/ui/settings/app:dynatrace.kubernetes.connector:connection?gf=all) should be created and deleted after CR deletion
> 
> could you please add ticket link to description?

@andriisoldatenko there is no ticket. It's a quick suggested change! :+1:

**Comment by andriisoldatenko** [comment]
gotcha, LGTM

**Review by StefanHauth — APPROVED** [review]
LGTM

**Pull request merged**
