### PR TITLE
Enable the usage of verbosity levels for logging

### PR DESCRIPTION
**Pull request by StefanHauth**
## Description

The main purpose of this PR is to straighten our logging and make the usage of verbosity levels (aka. `log.V(n)` possible. This also includes a bit of refactoring and code cleanup. This PR intentionally does not change existing log lines or introduce lot's of debug logging. That's for later. Also the actual log output should be kept as close as possible to what we have now.

This PR is split in two commits to make reviewing a bit easier. 
* 2952d2ad8ff45cb54c380004e256e27cc4527cd3 get's rid of a useless factory pattern. This one touches lot's of files. 
* The core refactoring is in 21e6c151d569468d089462fa67551a0f3b8c5e14.

## How can this be tested?

Deploy the operator and check if logs are still arriving and are readable (at least as readable as they used to be ;-)

## Checklist

- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly with a single label
- [x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by 0sewa0** [comment]
> https://github.com/Dynatrace/dynatrace-operator/commit/2952d2ad8ff45cb54c380004e256e27cc4527cd3 get's read of a useless factory pattern. This one touches lot's of files.

That weird factory pattern was introduced to minimise memory usage.
I can't explain why "it worked", but it did, and I also can't tell if your current implementation would undo this "optimisation" or not.

but I would definitely check if the memory usage does not do anything scary

**Comment by StefanHauth** [comment]
> > [2952d2a](https://github.com/Dynatrace/dynatrace-operator/commit/2952d2ad8ff45cb54c380004e256e27cc4527cd3) get's read of a useless factory pattern. This one touches lot's of files.
> 
> That weird factory pattern was introduced to minimise memory usage. I can't explain why "it worked", but it did, and I also can't tell if your current implementation would undo this "optimisation" or not.
> 
> but I would definitely check if the memory usage does not do anything scary

Will do!

**Comment by wepudt** [comment]
the logging part works for me.

**Comment by StefanHauth** [comment]
> > [2952d2a](https://github.com/Dynatrace/dynatrace-operator/commit/2952d2ad8ff45cb54c380004e256e27cc4527cd3) get's read of a useless factory pattern. This one touches lot's of files.
> 
> That weird factory pattern was introduced to minimise memory usage. I can't explain why "it worked", but it did, and I also can't tell if your current implementation would undo this "optimisation" or not.
> 
> but I would definitely check if the memory usage does not do anything scary

Fixed in [e02be6c](https://github.com/Dynatrace/dynatrace-operator/pull/2659/commits/e02be6c548f173e794da8f131dfdaef0d7283946)

**Review by wepudt — APPROVED** [review]
lgtm

**Pull request merged**
