### PR TITLE
Create an ActiveGate CR

### PR DESCRIPTION
**Pull request by gkrenn**
## Description

We want to split out the ActiveGate section into its own CR, the first step is to just move what we currently have that is ActiveGate related into its own CR.

## How can this be tested?

- `make deploy` => check if activegate crd is in the cluster. 
- `make doc` => updated docs are in the corresponding folder

## Checklist

- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly with a single label
- [x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Review by 0sewa0 — COMMENTED** [review]
would it make sense to also copy the activegate relevant parts from the `properties.go`?

like: https://github.com/Dynatrace/dynatrace-operator/blob/bfc7158e1d3edea7352a17e2c343a952aa428d7e/pkg/api/v1beta1/dynakube/properties.go#L273-L283

**Comment by aorcholski** [comment]
also global variables 

https://github.com/Dynatrace/dynatrace-operator/blob/87868242c6edc23a96fa5f2197eca5cb4ea28fe8/pkg/api/v1beta1/dynakube/activegate_types.go#L47-L52

https://github.com/Dynatrace/dynatrace-operator/blob/87868242c6edc23a96fa5f2197eca5cb4ea28fe8/pkg/api/v1beta1/dynakube/properties.go#L130-L144

**Review by aorcholski — APPROVED** [review]
LGTM

**Comment by wepudt** [comment]
deployment works fine, CRD is there.
but when doing `make doc` I got an error:
```
# Generate openshift-csi.yaml
helm template dynatrace-operator config/helm/chart/default \
		--namespace dynatrace \
		--set partial="csi" \
		--set platform="openshift" \
		--set manifests=true \
		--set olm="false" \
		--set image=""quay.io/dynatrace/dynatrace-operator:snapshot-feature-create-activegate-cr"" > "config/deploy/openshift/openshift-csi.yaml"
cat "config/deploy/openshift/openshift.yaml" "config/deploy/openshift/openshift-csi.yaml" > "config/deploy/openshift/openshift-all.yaml"
python3 ./hack/doc/custom_resource_params_to_md.py ./config/crd/bases/dynatrace.com_activegates.yaml > ./doc/api/activegate-api-ref.md
Traceback (most recent call last):
  File "/Users/werner.putschoegl/dev/op/./hack/doc/custom_resource_params_to_md.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by gkrenn** [comment]
That's a python error indicating that you don't have all packages installed required for our doc generation.
AFAIR you need to install the following packages on your mac: 
- `pip3 install pyyaml`
- `pip3 install argparse`

**Review by 0sewa0 — APPROVED** [review]

**Pull request merged**
