### PR TITLE
Add golangci-lint gh action to renovate

### PR DESCRIPTION
**Pull request by andriisoldatenko**
## Description

Currently we updating golangci-lint only in makefiles, this PR updates logic, so we update it in GH version too.

## How can this be tested?

Please include some guiding steps on how to test this change during a review.

Tested in my fork:
https://github.com/andriisoldatenko/dynatrace-operator/pull/5

## Checklist

~- [ ] Unit tests have been updated/added~
- [x] PR is labeled accordingly with a single label
- [x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by albertogdd** [comment]
Nice to use regex101 to try it out :+1: 
You can also share a link from that page with the regex already written and the test string (so the reviewer doesn't have to replicate it)

**Review by albertogdd — APPROVED** [review]

**Comment by andriisoldatenko** [comment]
Currently, I'm testing this change in my fork.

**Comment by andriisoldatenko** [comment]
Tested in my [fork ](https://github.com/andriisoldatenko/dynatrace-operator/pull/5)

**Review by StefanHauth — APPROVED** [review]
Seems to work on your fork, so LGTM.

**Pull request merged**
